import { Metadata } from 'next'

export const metadata: Metadata = {
  alternates: { canonical: '/terms' },
  title: 'Terms of Service - Fridge AI',
  description:
    'Terms of Service for Fridge AI — subscriptions, acceptable use, AI output and food safety disclaimers, and liability.',
  keywords: 'terms of service, terms of use, subscription terms, EULA, user agreement',
}

/**
 * Terms of Service — published 2026-08-02.
 *
 * WHY THIS PAGE EXISTS: App Store Review Guideline 3.1.2 requires a subscription
 * purchase screen to link to Terms of Use. The app's paywall links here, so if
 * this route 404s the app is rejected. It previously did — the footer pointed
 * "Terms of Service" at /support, which is a support page, not terms.
 *
 * Source of truth: fridge-ai repo → legal/terms-of-service.md. Keep the two in
 * sync; if you edit one, edit the other.
 *
 * ⚠️ NOT YET REVIEWED BY AN ATTORNEY (as of 2026-08-02). Published because
 * having reasonable terms beats having none and Apple requires the page to
 * exist. Get this reviewed before meaningful revenue.
 */
export default function TermsPage() {
  return (
    <main className="min-h-screen bg-white py-20 px-4">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-4xl font-bold text-gray-900 mb-8">Terms of Service</h1>
        <div className="prose prose-lg max-w-none">
          <p className="text-gray-600 mb-8">Last Updated: August 2, 2026</p>

          <p className="text-gray-600 mb-8">
            By using the Fridge AI app (the &ldquo;App&rdquo;), you agree to these terms. Please read
            them, particularly the Food &amp; Recipe Disclaimer, which is part of these terms.
          </p>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">The Service</h2>
            <p className="text-gray-600">
              Fridge AI analyzes photos of your fridge and suggests recipes, with estimated
              ingredients, macros, and costs. Output is generated by artificial intelligence and
              provided for informational purposes only — see the Food &amp; Recipe Disclaimer below.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Subscriptions</h2>
            <ul className="list-disc pl-6 text-gray-600 mb-4">
              <li>
                Fridge AI offers a free tier of 3 scans per day. Unlimited scanning requires a paid
                subscription: <strong>$59.99 per year</strong> or <strong>$9.99 per month</strong>,
                each with a <strong>3-day free trial</strong>.
              </li>
              <li>
                <strong>
                  Trials automatically convert to a paid subscription unless canceled at least 24
                  hours before the trial ends.
                </strong>
              </li>
              <li>
                Manage or cancel anytime in your App Store or Google Play account settings.
                <strong> Deleting the App does not cancel a subscription.</strong>
              </li>
              <li>Payments and refunds are handled by Apple or Google under their own terms.</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Acceptable Use</h2>
            <p className="text-gray-600">
              Don&rsquo;t misuse the App: no reverse engineering, scraping, reselling output at
              scale, uploading unlawful content, or using the App in a way that violates applicable
              law. We may suspend accounts that abuse the service, such as automated bulk scanning.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Content and License</h2>
            <p className="text-gray-600">
              You retain rights to your photos. You grant us a limited license to process them in
              order to provide the service — see our{' '}
              <a href="/privacy" className="text-green-700 underline">
                Privacy Policy
              </a>{' '}
              for retention details. Recipes generated for you may be similar or identical to
              recipes generated for others; you are free to cook, save, and share them.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">AI Output Disclaimer</h2>
            <p className="text-gray-600">
              Ingredient detection and recipes are AI-generated estimates and can be wrong —
              including missed items, mislabeled items, and inaccurate calorie, macro, or cost
              estimates. Verify before you rely on them.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">
              Food &amp; Recipe Disclaimer
            </h2>
            <ul className="list-disc pl-6 text-gray-600 mb-4">
              <li>
                <strong>
                  Recipes are suggestions, not professional dietary, nutritional, or medical advice.
                </strong>
              </li>
              <li>
                <strong>Always verify food freshness and safety yourself.</strong> The App cannot
                tell whether food is spoiled.
              </li>
              <li>
                <strong>
                  Cook raw meat, poultry, seafood, and eggs to safe internal temperatures
                </strong>
                , regardless of how a recipe describes an ingredient. When in doubt, assume meat is
                raw.
              </li>
              <li>
                <strong>You are responsible for checking allergies and dietary restrictions.</strong>{' '}
                Diet filters such as vegan or gluten-free are best-effort AI output, not a
                guarantee.
              </li>
              <li>Macros and costs are rough estimates.</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Liability</h2>
            <p className="text-gray-600">
              To the maximum extent permitted by law, the App is provided &ldquo;as is,&rdquo; and
              our total liability is limited to the amount you paid us in the 12 months before a
              claim. We are not liable for indirect or consequential damages, including those
              arising from cooking decisions made with AI-generated content.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">
              Changes and Termination
            </h2>
            <p className="text-gray-600">
              We may update these terms, with material changes posted on this page, and may
              discontinue the service with reasonable notice. These terms are governed by the laws
              of the State of Texas, United States.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Contact</h2>
            <p className="text-gray-600">
              Questions about these terms? Email{' '}
              <a href="mailto:support@getfridgeai.com" className="text-green-700 underline">
                support@getfridgeai.com
              </a>
              .
            </p>
          </section>
        </div>
      </div>
    </main>
  )
}
